apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: echo-hello-person
spec:
  params:
    - name: person
      description: Person to greet
      default: Paolo
      type: string
  steps:
    - name: echo
      image: registry.redhat.io/rhel7:latest
      command:
        - echo
      args:
        - "Hello $(params.person)"

